version: '3'
services:
  api:
    container_name: api
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
       - ./apps/api/.env
    depends_on:
      - directus
    networks:
      - directus
    command: ["yarn", "start"]
  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus
  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./public/uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
    env_file:
      - ./apps/directus/.env
networks:
  directus:
