version: '3'
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - 3000:3000
    env_file:
       - ./apps/api/.env
    depends_on:
      - directus
    networks:
      - directus
  directus:
    container_name: directus
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./public/uploads:/directus/uploads
    networks:
      - directus
    env_file:
      - ./apps/directus/.env
  hooks:
    container_name: hooks
    build:
      context: ./
      dockerfile: Dockerfile.hooks
    ports:
      - 4000:4000
    networks:
      - directus
    env_file:
      - ./apps/hooks/.env
  dashboard:
    container_name: dashboard
    build:
      context: ./
      dockerfile: Dockerfile.dashboard
    ports:
      - 4001:4001
    networks:
      - directus
    env_file:
      - ./apps/dashboard/.env
networks:
  directus:
