version: '3'
services:
  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    volumes:
      - .caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - happypath
  api:
    image: ghcr.io/gokceno/happy-path-api:2.0.0
    env_file:
       - .api.env
    depends_on:
      - directus
    networks:
      - happypath
  directus:
    image: directus/directus:10.8.3
    networks:
      - happypath
    env_file:
      - .directus.env
  hooks:
    image: ghcr.io/gokceno/happy-path-hooks:2.0.0
    networks:
      - happypath
    env_file:
      - .hooks.env
  dashboard:
    image: ghcr.io/gokceno/happy-path-dashboard:2.0.0
    networks:
      - happypath
    env_file:
      - .dashboard.env
networks:
  happypath:
