version: '3'
services:
  api:
    container_name: api
    build:
      context: ./apps/api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
       - ./apps/api/.env
    depends_on:
      - directus
    networks:
      - directus
    command: ["yarn", "start"]
  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./public/uploads:/directus/uploads
    networks:
      - directus
    env_file:
      - ./apps/directus/.env
  hooks:
    container_name: hooks
    build:
      context: ./apps/hooks/
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - directus
    env_file:
      - ./apps/hooks/.env
networks:
  directus:
