version: '3'
services:
  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus
  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./public/uploads:/directus/uploads
    networks:
      - directus
    depends_on:
      - cache
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: ''
      DB_PORT: ''
      DB_DATABASE: ''
      DB_USER: ''
      DB_SSL__REQUIRE: true
      DB_SSL__REJECT_UNAUTHORIZED: false
      DB_SSL__CA: ''
      DB_PASSWORD: ''
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      NODE_TLS_REJECT_UNAUTHORIZED: false
      # PUBLIC_URL: 'https://directus.example.com'
networks:
  directus:
