# Specify a base image
FROM node:18 AS build 

LABEL org.opencontainers.image.source = "https://github.com/gokceno/happy-path-time-tracker"

# Change working directory
WORKDIR /usr/app

# Copy in the app and weights
COPY ./ /usr/app

# Install dependencies
RUN yarn global add turbo
RUN yarn install
RUN turbo build --env-mode=loose

EXPOSE 4001

CMD turbo start --filter='./apps/dashboard' --env-mode=loose