name: Docker Image CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Get NPM version for API
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Build API
      uses: docker/build-push-action@v5.0.0
      with:
        context: Dockerfile.api
        push: true
        tags: |
          ghcr.io/gokceno/happy-path-api:latest
          ghcr.io/gokceno/happy-path-api:${{ steps.package-version.outputs.current-version}}
    - name: Build Auth
      uses: docker/build-push-action@v5.0.0
      with:
        context: Dockerfile.auth
        push: true
        tags: |
          ghcr.io/gokceno/happy-path-auth:latest
          ghcr.io/gokceno/happy-path-auth:${{ steps.package-version.outputs.current-version}}
    - name: Build Dashboard
      uses: docker/build-push-action@v5.0.0
      with:
        context: Dockerfile.dashboard
        push: true
        tags: |
          ghcr.io/gokceno/happy-path-dashboard:latest
          ghcr.io/gokceno/happy-path-dashboard:${{ steps.package-version.outputs.current-version}}
    - name: Build Hooks
      uses: docker/build-push-action@v5.0.0
      with:
        context: Dockerfile.hooks
        push: true
        tags: |
          ghcr.io/gokceno/happy-path-hooks:latest
          ghcr.io/gokceno/happy-path-hooks:${{ steps.package-version.outputs.current-version}}